name: Neural Window Package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install CUDA Toolkit
      uses: Jimver/cuda-toolkit@v0.2.11
      id: cuda-toolkit
      with:
        cuda: '12.1.0'
    - name: Install Intel MKL
      run: sudo apt-get install -y intel-mkl
    - name: Install OpenBLAS
      run: sudo apt-get install -y libopenblas-dev
    - name: Install Check
      run: sudo apt-get install -y check
    - name: Install Valgrind
      run: sudo apt-get install -y valgrind
    - name: Install Libtorch
      run: |
        sudo wget https://download.pytorch.org/libtorch/cpu/libtorch-shared-with-deps-2.0.1%2Bcpu.zip
        unzip libtorch-shared-with-deps-2.0.1+cpu.zip
    - name: Setup Build Directory
      working-directory: ${{github.workspace}}
      run: mkdir build
    - name: GPU Build
      working-directory: ${{github.workspace}}/build
      run: |
        cmake -DCMAKE_PREFIX_PATH=../libtorch/ ..
        make
    - name: CPU Build
      working-directory: ${{github.workspace}}/build
      run: |
        CPU_ONLY=1 cmake -DCMAKE_PREFIX_PATH=../libtorch/ ..
        make
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest --output-on-failure
    - name: Memory Tests
      working-directory: ${{github.workspace}}/build
      run: |
        make valgrind_test_buffer_binary
        make valgrind_test_buffer_reduction
        make valgrind_test_buffer_unary
        make valgrind_test_map
        make valgrind_test_queue
        make valgrind_test_tensor_reduction
        make valgrind_test_tensor_unary
        make valgrind_test_view